import Footer from "./_components/Footer";
import NavBar from "./_components/NavBar";
import WatchlistMigration from "./_components/WatchlistMigration";
import "./globals.css";
import SessionProviderWrapper from "./_components/SessionProvider";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" precedence="default" />

      <body className="bg-gray-50 dark:bg-gray-900 text-gray-900 dark:text-white min-h-screen">
          <SessionProviderWrapper>
            <NavBar/>
              {children}
            <Footer/>
            <WatchlistMigration />
          </SessionProviderWrapper>
      </body>
    </html>
  );
}
